# Generated by Django 6.0.7 on 2026-07-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drive_link', models.URLField()),
                ('image', models.ImageField(upload_to='functions/')),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears on website')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_text', models.CharField(help_text='e.g. 9th Dec 2026', max_length=50)),
                ('time_text', models.CharField(help_text='e.g. 10:00 AM Onwards', max_length=50)),
                ('dress_code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='programs/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeddingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default='Ansh', max_length=50)),
                ('bride_name', models.CharField(max_length=50)),
                ('wedding_date', models.DateTimeField(help_text='Format: YYYY-MM-DD HH:MM:SS')),
                ('master_drive_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
