# Generated by Django 6.0.7 on 2026-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingdetail',
            name='city',
            field=models.CharField(default='Bhopal', help_text='e.g. Bhopal, Indore', max_length=50),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='contact_1_name',
            field=models.CharField(default='Family Member 1', max_length=50),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='contact_1_phone',
            field=models.CharField(default='+91 98765 43210', max_length=20),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='contact_2_name',
            field=models.CharField(blank=True, default='Family Member 2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='contact_2_phone',
            field=models.CharField(blank=True, default='+91 98765 43211', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed SRC link', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='venue_address',
            field=models.TextField(default='', help_text='Complete address with Pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingdetail',
            name='venue_name',
            field=models.CharField(default='Lotus City', max_length=100),
        ),
    ]
